nama: ZyinXRdp

pada: alur kerja_dispatch

pekerjaan:

  membangun:

    berjalan-on: windows-terbaru

    menit-waktu habis: 9999

    Langkah:

    - Nama : Download Ngrok.

      lari: |

        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

        Invoke-WebRequest https://raw.githubusercontent.com/HarChanel90/Rdp-Gratis-by-Har-Chanel/main/start.bat -OutFile start.bat

        Invoke-WebRequest https://raw.githubusercontent.com/HarChanel90/Rdp-Gratis-by-Har-Chanel/main/download.jpeg -OutFile wallpaper.bat

        Invoke-WebRequest https://raw.githubusercontent.com/HarChanel90/Rdp-Free-By-ZyinX/main/loop.bat -OutFile loop.bat

    - nama : Ekstrak File Ngrok.

      jalankan: Perluas-Arsip ngrok.zip

    - Nama : Sambung Ngrok.

      jalankan: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      lingkungan:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Windows10 RDP.

      run: |

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

        copy wallpaper.bat D:\a\wallpaper.bat

    - name: Tunnel.

      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'

    - name: Connect Rdp.

      run: cmd /c start.bat

    - name: win10 RDP.

      run: cmd /c loop.bat
